### ISSUE TITLE
Sort by name does not work

### ISSUE THREAD

**Issue by therestoftheday** [esyede/php-dirlister#1]
Hello

As shown on your capture, the sorting by name seems quite strange. I cannot really understand what the sorting order when trying to sort files list by name...

![image](https://github.com/esyede/php-dirlister/assets/25632055/fa43914e-585a-4776-8d7a-d1fe67349006)

![image](https://github.com/esyede/php-dirlister/assets/25632055/a704cb8b-dc0d-4f22-9641-36aad99c254d)

If you could help that would be great because i really enjoy this "minimal" tool.

Thanks.

### Info
PHP Version 8.2.18

**Comment by esyede** [comment]
Hi!
I cannot reproduce the issue in PHP 8.2.20; can you elaborate more?

https://github.com/esyede/php-dirlister/assets/10582583/d5bfc2f3-abba-4816-a925-e9bb305dab3c

**Comment by therestoftheday** [comment]
Well i do the same as you and my files are still displayed in wrong order.
Take a look at the screen capture you made : it seems like your files should be sorted by filenames (check the arrow) but they are not. 
[image](https://github.com/esyede/php-dirlister/assets/25632055/8031d84a-44f0-45ec-9d32-e9ee432ce489)

I send you a video as soon as possible.

**Comment by therestoftheday** [comment]
Here is the video :
[download_07-06-12_40_17-ezgif.com-video-cutter.webm](https://github.com/esyede/php-dirlister/assets/25632055/155a08e5-8106-4294-9673-e20d0f57591a)

**Comment by therestoftheday** [comment]
https://github.com/esyede/php-dirlister/assets/25632055/9ff35860-3d65-4389-889c-6c197b015483

**Comment by esyede** [comment]
> Well i do the same as you and my files are still displayed in wrong order. Take a look at the screen capture you made : it seems like your files should be sorted by filenames (check the arrow) but they are not. [image](https://github.com/esyede/php-dirlister/assets/25632055/8031d84a-44f0-45ec-9d32-e9ee432ce489)
> 
> I send you a video as soon as possible.

Hmm, seems like it behaves differently on Windows. I tested that on Windows, btw. Let me upload it test it on a Linux machine, and check.

**Comment by esyede** [comment]
Hi!
Fix added on https://github.com/esyede/php-dirlister/commit/dee83e559a8bb6069c9a9ae2d33c161f6e05772c
Can you test it again?
Thanks!

**Comment by therestoftheday** [comment]
Works great ! Thanks 👍
